### ISSUE TITLE
ModuleNotFoundError: No module named '_learn'

### ISSUE THREAD

**Issue by user360** [flaviovdf/tribeflow#4]
I installed all the dependencies and I have no errors while running make but when I tried to run main.py it shows:

> Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from tribeflow import dataio
  File "/home/h_anh/tribeflow/tribeflow/__init__.py", line 10, in <module>
    from tribeflow.learn import fit
  File "/home/h_anh/tribeflow/tribeflow/learn.py", line 4, in <module>
    from _learn import em
ModuleNotFoundError: No module named '_learn'

**Comment by flaviovdf** [comment]
Did you compile using make? Also, are you using python2?

**Comment by flaviovdf** [comment]
Since there was no response im closing this.
