### ISSUE TITLE
RSS.dat and the format of prediction.dat

### ISSUE THREAD

**Issue by hungpthanh** [flaviovdf/tribeflow#6]
Hi flaviovdf,
I have some questions.
1.What is RSS.DAT and RSS's format is similar to test_parser's format?
2. When I run prediction sample, I found a float number in output. Is this MRR number? And Can you explain the meaning of  numbers in prediction.dat to me?
Thank you very much!

**Comment by flaviovdf** [comment]
Which script are you using?

**Comment by hungpthanh** [comment]
@flaviovdf  I am really sorry for my late reply. Recently, I need to run your code, and I suddenly remember my question. Now, I think that I have found my mistake. RSS.dat is not input data, it just is a file that contains rss value. Input data is stored in the model. Oh my God :( My memory is really bad :( One more time, I am sorry :(
